version: "3.5"


services:
  build-site:
    build: 
      context: ./
    command: bundle exec jekyll build
    volumes:
      - .:/app
  serve:
    build:
      context: ./
    ports:
      - 4000:4000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t



# When you specify a command for a service in the Docker Compose file, it overrides the CMD instruction in the Dockerfile. So in your case, the command specified in the serve service will be used instead of the CMD instruction in the Dockerfile when you run the container.
# However, it's still a good idea to include the CMD instruction in the Dockerfile as a fallback in case the command is not specified in the Docker Compose file.