name: Docker Compose Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Update jekyll-anchor-headings
      id: update
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/allejo/jekyll-anchor-headings/releases/download/${{ steps.latest-release.outputs.release }}/anchor_headings.html"
        target: _includes/vendor/
        
    - name: Build and run Docker Compose (jekyll build)
      run: |
        docker-compose build
        docker-compose up build-site
        pwd
        ls -la


    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        cname: www.hackthisbadge.com